### ISSUE TITLE
Bug of waste of items in the inventory

### ISSUE THREAD

**Issue by atx150w** [KryptonIon/ItemModifier#2]
hello i have problem with this mod, he make me throw away my items on inventory, he make me use the item twice when i click on an empty area of ​​the map, the item is thrown out of the inventory without me making use of it, just by clicking with the left mouse button terraria 1.3.5.3 tmodloader v0.11.6.2

**Comment by KryptonIon** [comment]
Hi! Can you be more clear about `he make me throw away my items on inventory` and `he make me use the item twice when i click on an empty area of ​​the map`? Also, are you using TModLoader 64bit? The mod isn't compatible with that version of TModLoader. If not, can you send me your client.log located in
Windows: `%UserProfile%\Documents\My Games\Terraria\ModLoader\Logs` (This is typically found in C:\Documents\)
Linux: `~/.local/share/Terraria/ModLoader/Logs/ or $XDG_DATA_HOME/Terraria/ModLoader/Logs/`
Mac: `~/Library/Application support/Terraria/ModLoader/Logs/`.
